sudo: required
services:
  - docker
before_install:
  - docker build -t thinktwice13/xmultidocker-react -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true thinktwice13/xmultidocker-react npm test -- --coverage
after_success:
  - docker build -t thinktwice13/xmultidocker-worker:k8s ./worker
  - docker build -t thinktwice13/xmultidocker-api:k8s ./api
  - docker build -t thinktwice13/xmultidocker-client:k8s ./client
  - docker build -t thinktwice13/xmultidocker-nginx:k8s ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thinktwice13/xmultidocker-worker:k8s
  - docker push thinktwice13/xmultidocker-api:k8s
  - docker push thinktwice13/xmultidocker-client:k8s
  - docker push thinktwice13/xmultidocker-nginx:k8s
# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   region: us-east-1
#   app: xmultidocker
#   env: xmultidocker-env
#   bucket: elasticbeanstalk-us-east-1-001868528084
#   on:
#     branch: master
