apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: complex
build:
  local: {}
  artifacts:
    - image: thinktwice13/xmultidocker-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: thinktwice13/xmultidocker-api
      context: api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: thinktwice13/xmultidocker-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
deploy:
  kubectl:
    manifests:
      - k8s/client-config.yaml
      - k8s/api-config.yaml
      - k8s/worker-config.yaml
