apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pg
  template:
    metadata:
      labels:
        component: pg
    spec:
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
      containers:
        - name: pg
          image: postgres:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: pg
  ports:
    - port: 5432
      targetPort: 5432
