apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: thinktwice13/xmultidocker-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          # no need for ports (or services) because nothing will be connecting inbound to this worker
          # ports:
          #   - containerPort: <Port>
